### ISSUE TITLE
Unspecified launch error, DRIVER 719 in run_single_stream, errors, etc.

### ISSUE THREAD

**Issue by kyleboddy** [nicehash/excavator#107]
Getting these unspecified errors on cards running fully stock, no overclocking. Searching the issues didn't come up with much. Any idea? GTX 1060s, all benchmarked to Standard.

![image](https://user-images.githubusercontent.com/746351/34875994-81b60c40-f754-11e7-89cf-08c71e03b347.png)

**Comment by dropky** [comment]
What driver version are you currently using? Have you tried downloading the latest driver version?

**Comment by dropky** [comment]
Please take a look at #108 and let me know if anything mentioned there solves your problem (downgrading the drivers, a recheck of risers, check if your PSU is powerful enough).

**Comment by kyleboddy** [comment]
PSU plenty powerful enough, risers are fine, may try downgrading drivers in the future but its just not that impactful right now I guess.

**Comment by jace808** [comment]
I have a very similar error to this.  I have 6 1080 tis... 3 ASUS strix 11gb & 3 EVGA ftw3 11gb cards.  I have 2 seasonic titanium 1000w power supplies.  I have swapped out risers and cards.  I don't recall seeing the "unspecified launch failure" error but I have seen the 'run_single_stream' error every time I try to run equihash algo (i only mine equihash and lyra2rev) on nicehash.  I can run dstm equihash at higher clock rates with no issue.  Most of the time I see the error and 1 of my EVGA cards stops communicating and nicehash restarts excavator or crashes.  It seems to always be a EVGA card that stops however nicehash says its an ASUS card.  I know this is not the case because the EVGA fans aren't spinning and all ASUS card fans are.

**Comment by dropky** [comment]
@jace808 Try changing the overclocking settings. If it always crashes on the same card, set it to stock settings and then slowly apply overclocking until you find a stable state.

**Comment by jace808** [comment]
It's not the same card, it's all 3 of my EVGA 1080 TI FTW3 cards.  They completely power off and that's with 80%/-16/0.  The 3 STRIX cards continue on.

**Comment by nicehashdev** [comment]
This algorithm is not supported anymore. Closing.
