### ISSUE TITLE
V2.0.1.8 Starting Excavator Stuck

### ISSUE THREAD

**Issue by HalpMePlz** [nicehash/excavator#127]
Keep getting stuck on "Starting Excavator". Searched around for solutions and nothing seems to be working. Suggestions related to firewall, driver signature enforcement, etc. do not work. Saw another thread where a user was queried whether they had an excavator.exe file in their C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_server, and I apparently don't. 

Any suggestions welcome. Thanks!

**Comment by dropky** [comment]
You can manually download excavator from here: https://github.com/nicehash/excavator/releases and put it in `C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_server `directory. If excavator.exe gets auto-deleted you should recheck your antivirus.

**Comment by blackthoghts** [comment]
Getting an error
SMA Is down.
You are unable to mine because there are sma service issues. 

What does this mean?

**Comment by dropky** [comment]
@blackthoghts SMA is a simple multi-algorithm protocol that gets profitability information about algorithms and returns back most profitable algorithm (information that NHM requires in order to switch to the most profitable algorithm). There might be some issues on a server. If you're still getting this error open a support ticket. Since this has nothing to do with excavator there isn't much I can do.
