### ISSUE TITLE
Add total power consumption/efficiency to WebUI

### ISSUE THREAD

**Issue by Anx2k** [nicehash/excavator#131]
Minor feature suggestion, but it would be very handy if the Web UI had a section between the list of cards, and the algorithm info, that reported the efficiency of the rig.  Basically this would just be the sum of all the Power Usage values for all the cards (display this also, as it would be handy to know the total rigs wattage), and then divide by the hash rate so the watts per hash are known.

**Comment by EvgeniyKorepov** [comment]
Maybe my application will help you https://github.com/Kayfolom/ExcavatorMonitor

**Comment by Anx2k** [comment]
We have our own internal system that we monitor multiple rigs with - I just thought it would be a nice addition for new users, and when I've recommended Excavator to other people they've asked about it (probably because they've seen our system).

**Comment by dropky** [comment]
@Anx2k There is one problem with your suggestion, how would you calculate the efficiency per rig (hashes / watt) if there are multiple different algorithms running on the same rig?

For example:
rig with 2 x 1070, running lbry on the first card and daggerhashimoto on the second

lbry: 300 MH/s, 166.00 W
daggerhashimoto: 27 MH/s, 128.00 W 

You're proposing that efficiency of this rig would be: (300 MH + 27 MH) / (166 W + 128 W) = 327 MH / 294W = 1,1 MH / W 

This is not accurate at all since hashrate of lbry is almost 12 times hashrate of dagger.

**Comment by Anx2k** [comment]
In that instance, I would just print the efficiency of each algorithm - really just to get a sense of how well the rig is tuned.

**Comment by dropky** [comment]
Ok, there is still a problem with the dual mining, but I'll figure something out :) I'll keep you updated.

**Comment by agiz** [comment]
Hi @Anx2k, we will add this in the next release.

**Comment by Anx2k** [comment]
Great - can't wait!  :)

**Comment by nicehashdev** [comment]
Web not supported anymore. Closing.
