### ISSUE TITLE
Core Initialized hang

### ISSUE THREAD

**Issue by tutulino** [nicehash/excavator#135]
I tested different algos, different machines and always get same result, excavator hangs on this point

![image](https://user-images.githubusercontent.com/29943663/35193418-6346cba0-fea2-11e7-928e-16ce2a68d54a.png)

**Comment by tutulino** [comment]
I did not know that log level option, now I see where "bug" is, algorithm name is case sensitive. I was using firts uppercase letter for algo name.

Thanks

**Comment by siulcode** [comment]
I'm getting the same errors since yesterday. It hangs forever on "core | Initialized!".

`Build time: 2018-02-02 09:28:47
Build number: 4511
Provided startup commandline:
        C:\Users\evga1080tirig1\AppData\Roaming\nhm2\bin\excavator_cuda9.1\excavator.exe   -p 4001 -na -d 0

[06:31:42][0x00002260][info] Log started
[06:31:42][0x00002260][info] core | Found CUDA device: GeForce GTX 1080 Ti
[06:31:43][0x00002260][info] core | Found CUDA device: GeForce GTX 1080 Ti
[06:31:43][0x00002260][info] core | Found CUDA device: GeForce GTX 1080 Ti
[06:31:43][0x00002260][info] core | Found CUDA device: GeForce GTX 1080 Ti
[06:31:43][0x00002260][info] core | Found CUDA device: GeForce GTX 1080 Ti
[06:31:43][0x00002260][info] api | Listening on 127.0.0.1:4001
[06:31:43][0x00002260][info] core | Initialized!
`
Reinstalled drivers and nicehash from scratch. Any tips would be greatly appreciated. 

Thanks.
LL.

**Comment by EvgeniyKorepov** [comment]
@siulcode Try using MinerPro https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash . You can use your rig for 5-10% more efficiently.

Command file ExcavatorServer.json :
```
[
	{"time":15,"loop":15,"commands":[
	  	{"id":1,"method":"algorithm.print.speeds","params":[]}
	]},
	{"event":"on_quit","commands":[
		{"id":1,"method":"device.set.tdp","params":["0","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["0","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","0"]},
		{"id":1,"method":"device.set.tdp","params":["1","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["1","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["1","0"]},
		{"id":1,"method":"device.set.tdp","params":["2","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["2","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["2","0"]},
		{"id":1,"method":"device.set.tdp","params":["3","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["3","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["3","0"]},
		{"id":1,"method":"device.set.tdp","params":["4","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["4","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["4","0"]}
	]}
]
```
Startup file (for example "#start.cmd") :
```
@echo off
:: CONFIG STARTS
SET LOCALDIR=%~dp0
SET CONSOLE_LOG_LEVEL=2
SET FILE_LOG_LEVEL=0
SET WEB_PORT=38080
SET WEB_HOST=0.0.0.0
SET TOKEN=MyCoolToken
SET PORT=33333
SET HOST=0.0.0.0
SET RESTART_DELAY=0
:: CONFIG ENDS
cd /d "%LOCALDIR%"
:start
SET COMMAND_FILE=ExcavatorServer.json

excavator.exe -c %LOCALDIR%%COMMAND_FILE% -d %CONSOLE_LOG_LEVEL% -f %FILE_LOG_LEVEL% -wp %WEB_PORT% -wi %WEB_HOST% -wa %TOKEN% -p %PORT% -i %HOST%  

timeout /T %RESTART_DELAY%
goto start
```

Create both files in the Excavator folder  and run #start.cmd

**Comment by dropky** [comment]
@siulcode Could you post the whole cmd output? It looks like you're not adding any algorithms. Are you using config file or NHM2?

**Comment by webmetender** [comment]
Hi there

same as @siulcode, reinstalled nicehash and drivers.

No overclock on 6 nvidia cards, temps are around 60c.

After some time nicehash restarts and then hangs on "core | Initialized!".

When excavator crashes, it restarts fast and nicehash logs do not contain anything about the error that caused the crash: is there a way to log the errors which cause excavator restart?

Thanks,

A.

**Comment by dropky** [comment]
@webmetender Yes, you have to enable excavator logs. 
Go to `C:\Users\user_name\AppData\Roaming\nhm2\configs` folder and edit `General.json` file. Add -f 0 parameter to ExcavatorExtraStartupParameters ("ExcavatorExtraStartupParameters": "-f 0"), restart NHM and wait for the crash. You'll find the logs in `C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_cuda9.1\archived_logs` directory if you're using drivers 387.xx or more recent otherwise check `C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_server\archived_logs` folder.

Note: After the crash, you should remove -f 0 parameters from the General.json file and restart NHM again to disable excavator logging (otherwise it could take up quite a lot of disk space).

**Comment by siulcode** [comment]
@dropky things seem to be working now. Maybe some NH services were down or something.

**Comment by webmetender** [comment]
@dropky thank you for the logs tip!
