### ISSUE TITLE
Can’t  run bat (win7 sp1 64bit GTX 1070)

### ISSUE THREAD

**Issue by sfx12311** [nicehash/excavator#14]
Even use the default json file and bat,but still failed like:
Build number: 412
Provided startup commandline:
        excavator.exe  -c default_command_file.json -d 2 -f 6 -p 0 -wp 38080 -wi
 127.0.0.1 -wa

[23:59:06][0x001ebe18][info] Log started
Excavator has crashed... restarting in 10 seconds...

The driver is 378.78.any help~ thanks

**Comment by Kayfolom** [comment]
This is due to attempts to load the library **phymem.sys** when necessary and not necessary.
On computers with Nvidia, this leads to sad consequences - the crash of the operating system, just freezing, or the error "it is not possible to run a 16 bit application".

Remove the library **phymem.sys** from the pack with the application and everything will work.

To Developers: try before downloading libraries, do you need to think it or not?

**Comment by sfx12311** [comment]
After delete phymem.sys file,the problem is still there. Now I choose another mine program to start mining already.Close this issue...
