### ISSUE TITLE
API method algorithm.list small nuance

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#174]
API method algorithm.list returns additional parameters of the worket (algorithms[i]/workers[k]/params) only if they are manually set.
It would be very, very good, if the default parameters were also returned.
Example:
send {"id":1,"method":"worker.add","params":["237","0"]} (with out additional params)
receive "workers": [{worker_id": 0,"device_id": 0,"params": ["NPT=32", "B=6900", "TPB=256"]...

Thank you in advance!

**Comment by dropky** [comment]
We're planning to add multiple changes to the API in the near future (will take into consideration this request as well).

**Comment by EvgeniyKorepov** [comment]
@dropky You can publish a list of optimized parameters for GPUs by algorithms? Thank you in advance!

**Comment by dropky** [comment]
That's quite a lot of parameters and we change them very often (due to changes in the implementation). We'll add them to API method. I'll let you know when we come to that. 

For now you can see them in the log/console output, when worker is assigned to the device, startup parameters are printed as well.

**Comment by nicehashdev** [comment]
This will be implemented in next version. Closing.
