### ISSUE TITLE
Lyra2REv2 gives HALF the hash-rate with Titan V

### ISSUE THREAD

**Issue by chara1ampos** [nicehash/excavator#199]
Results for Lyra2REv2 and Nvidia Titan V:

NHM 2.0.1.11 (excavator 1.4.4a): 48 MH/s
NHM Legacy 1.8.1.8 (ccminer): 102 MH/s 

That is less than half the hash-rate.

**Comment by dropky** [comment]
We're aware of the performance gap for Lyra2rev2 on Titan V and we're going to look into it as soon as possible.

**Comment by QCAGENT** [comment]
Do you recommend using Legacy until excavators are optimised for TitanV core?

**Comment by dropky** [comment]
Lyra2rev2 seems to be the only algorithm that is underperforming in excavator on Titan V. If you're gonna run lyra2rev2 then yes, I suggest you to use NHML in this case. Anyway, if I'm not mistaken, most of the time dual mining is the most profitable algorithm for Titan V.

**Comment by QCAGENT** [comment]
Got it!  I'm mainly looking to take advantage of Lyra2rev2 when its peaking high.  When that happens, all GPUs are focusing on Lyra2 while the TitanV sticks to DagHashi dual.   As a side note, the TitanV is not doing that great on most Algos.  Do you foresee any Driver/Algo improvements regarding the TitanV?

**Comment by dropky** [comment]
Yeah, that's understandable, especially since lyra2 isn't performing that great and dagger on the other hand is. Depends on the algorithm, on some is doing quite well (dagger for example, with a little overclock it can reach around 80MH/s). But yes, I completely agree with you that the card isn't reaching its full potential - it's capable of much more. We have a plan to work on improvements, but it's not our top priority right now.

**Comment by QCAGENT** [comment]
Well, I must admit I'm looking forward to those improvements.  I see the Titan V as a good long term Worker since it could perform well for the next 2-3 years.  Let me know if I can assist in any way. (Beta testing/config testing, etc)

**Comment by dropky** [comment]
Version 1.5.1a includes improvements on lyra2rev2 for Titan V.
