### ISSUE TITLE
 v1.4.4a_nvidia Randomly Crashes

### ISSUE THREAD

**Issue by salighie** [nicehash/excavator#216]
Hi, 

i'm getting random crashes with error 
 CUDA error 'unspecified launch failure' in func 'cuda_daggerhashimoto::run' line 1461

my setup is 4x EVGA GTX 1070ti SC Gaming / ROG Strix Z370-E mobo / i7-8700 / 2x 750w PSU

any ideas what could be going on ?

here's an excerpt from the excavator log:

[[2018-03-14 12:33:31.162229] [thread=0x00000514] [info]]Log started
[[2018-03-14 12:33:31.510432] [thread=0x00000514] [info]]core | Found CUDA device: GeForce GTX 1070 Ti
[[2018-03-14 12:33:31.697953] [thread=0x00000514] [info]]core | Found CUDA device: GeForce GTX 1070 Ti
[[2018-03-14 12:33:31.729207] [thread=0x00000514] [info]]core | Found CUDA device: GeForce GTX 1070 Ti
[[2018-03-14 12:33:31.760460] [thread=0x00000514] [info]]core | Found CUDA device: GeForce GTX 1070 Ti
[[2018-03-14 12:33:31.791713] [thread=0x00000514] [info]]api | Listening on 127.0.0.1:3456
[[2018-03-14 12:33:31.791713] [thread=0x00000514] [info]]http | Listening on 192.168.2.11:8080
[[2018-03-14 12:33:31.791713] [thread=0x00000514] [info]]core | Initialized!
[[2018-03-14 12:33:45.818171] [thread=0x00001198] [info]]net | Connecting to 169.62.79.78:3353 (daggerhashimoto.usa.nicehash.com)
[[2018-03-14 12:33:45.896303] [thread=0x00001198] [info]]net | Connected!
[[2018-03-14 12:33:46.115077] [thread=0x00001198] [info]]net | Authorized as MY_NH_BITCOINADDRESS.WORKERNAME
[[2018-03-14 12:33:46.130703] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000251e91aed7', diff=0.5
[[2018-03-14 12:33:47.251940] [thread=0x00000cd8] [info]]wrkr3-3 | Algorithm: CUDA-daggerhashimoto parameters: B=8189,TPB=128,HPW=4,S=1
[[2018-03-14 12:33:47.251940] [thread=0x00000cd8] [info]]job-daggerhashimoto | Generating DAG cache (08e704bf06ac983d)...
[[2018-03-14 12:33:47.251940] [thread=0x00000728] [info]]wrkr2-2 | Algorithm: CUDA-daggerhashimoto parameters: B=8189,TPB=128,HPW=4,S=1
[[2018-03-14 12:33:47.273714] [thread=0x00002918] [info]]wrkr0-0 | Algorithm: CUDA-daggerhashimoto parameters: B=8189,TPB=128,HPW=4,S=1
[[2018-03-14 12:33:47.273714] [thread=0x000020b0] [info]]wrkr1-1 | Algorithm: CUDA-daggerhashimoto parameters: B=8189,TPB=128,HPW=4,S=1
[[2018-03-14 12:33:50.923620] [thread=0x00000cd8] [info]]job-daggerhashimoto | DAG cache (08e704bf06ac983d) generation completed (3671ms)
[[2018-03-14 12:33:56.805237] [thread=0x00001198] [info]]core | Device #0-0 speed: 0.000000 H/s
...
[[2018-03-15 03:08:52.507436] [thread=0x00001198] [info]]net | Share #2896 accepted
[[2018-03-15 03:08:57.836608] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b719d96', diff=1
[[2018-03-15 03:09:05.326527] [thread=0x000026d0] [info]]core | Algorithm 'daggerhashimoto' total speed: 128.309183 MH/s
[[2018-03-15 03:09:08.840873] [thread=0x000026d0] [info]]algo-daggerhashimoto | New job_0 '000000252b71b77a', diff=1
[[2018-03-15 03:09:11.785704] [thread=0x00001198] [info]]core | Device #0-0 speed: 32.074675 MH/s
[[2018-03-15 03:09:11.789715] [thread=0x00001198] [info]]core | Device #1-1 speed: 32.074675 MH/s
[[2018-03-15 03:09:11.792723] [thread=0x00001198] [info]]core | Device #2-2 speed: 32.085157 MH/s
[[2018-03-15 03:09:11.793726] [thread=0x00001198] [info]]core | Device #3-3 speed: 32.074675 MH/s
[[2018-03-15 03:09:12.744254] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b725eaf', diff=1
[[2018-03-15 03:09:17.494887] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b729af1', diff=1
[[2018-03-15 03:09:22.124200] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b7346ce', diff=1
[[2018-03-15 03:09:23.686353] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b734bfe', diff=1
[[2018-03-15 03:09:27.947686] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b748823', diff=1
[[2018-03-15 03:09:32.324325] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b748e3a', diff=1
[[2018-03-15 03:09:36.325967] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b754e35', diff=1
[[2018-03-15 03:09:40.934222] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b760b5c', diff=1
[[2018-03-15 03:09:41.059556] [thread=0x00001198] [info]]algo-daggerhashimoto | New job_0 '000000252b760e4a', diff=1
[[2018-03-15 03:09:41.797518] [thread=0x000026d0] [info]]core | Device #0-0 speed: 32.057205 MH/s
[[2018-03-15 03:09:41.798521] [thread=0x000026d0] [info]]core | Device #1-1 speed: 32.057205 MH/s
[[2018-03-15 03:09:41.799523] [thread=0x000026d0] [info]]core | Device #2-2 speed: 32.064193 MH/s
[[2018-03-15 03:09:41.800526] [thread=0x000026d0] [info]]core | Device #3-3 speed: 32.057205 MH/s
[[2018-03-15 03:09:44.349304] [thread=0x00000728] [fatal]]wrkr2-2 | CUDA error 'unspecified launch failure' in func 'cuda_daggerhashimoto::run' line 1461
[[2018-03-15 03:09:44.360334] [thread=0x00000514] [info]]Shutting down
[[2018-03-15 03:09:44.360334] [thread=0x000020b0] [fatal]]wrkr1-1 | CUDA error 'unspecified launch failure' in func 'cuda_daggerhashimoto::run' line 1461
[[2018-03-15 03:09:44.373369] [thread=0x00002918] [fatal]]wrkr0-0 | CUDA error 'unspecified launch failure' in func 'cuda_daggerhashimoto::run' line 1461
[[2018-03-15 03:09:44.373369] [thread=0x00000cd8] [fatal]]wrkr3-3 | CUDA error 'unspecified launch failure' in func 'cuda_daggerhashimoto::run' line 1461
[[2018-03-15 03:09:45.684856] [thread=0x000026d0] [info]]algo-daggerhashimoto | New job_0 '000000252b763b6f', diff=1
[[2018-03-15 03:09:46.669474] [thread=0x000026d0] [info]]algo-daggerhashimoto | New job_0 '000000252b763d9b', diff=1
[[2018-03-15 03:09:50.291106] [thread=0x00000514] [info]]api | Closing
[[2018-03-15 03:09:50.294114] [thread=0x00000514] [info]]http | Closing

**Comment by salighie** [comment]
i've reviewed your [troubleshooter doc]( https://miner.nicehash.com/guides/NHM_troubleshooter_en.pdf) and increased the PageFile size to 42GB = 4*8GB (per card) + another 10 GB for the system.

Looking into the stock batch file in the release you have
:: AMD SPECIFIC SETTERS (DO NOT MODIFY!)
SET GPU_FORCE_64BIT_PTR=1
SET GPU_MAX_HEAP_SIZE=100
SET GPU_USE_SYNC_OBJECTS=1
SET GPU_MAX_ALLOC_PERCENT=100
SET GPU_SINGLE_ALLOC_PERCENT=100

should these still be there for NVIDIA cards?

**Comment by dropky** [comment]
You're right, the AMD related settings are not needed anymore, we're gonna remove them from the batch file in the upcoming release. 

Do you still encounter the crashes (even with increased virtual memory size)?

**Comment by salighie** [comment]
i'll have to restart without the AMD configurations and then monitor.

As you can see from the excerpt provided, it will run nicely -for days- then suddenly crash.

I'll let you know if it happens again, but it could be a while.

**Comment by gordan-bobic** [comment]
Sounds like OC instability to me. Run it at stock clocks and see if the problem goes away. If you are getting 32 MH/s - you are almost certainly running too OC-ed. You'll have to decide if you prefer random crashes at 32 MH/s or stability at 30 MH/s.

**Comment by salighie** [comment]
I do have them OC'd with EVGA's OCX at +150core +750mem 65%tdp (NOT OC;ed by any stretch of the imagination) 

I've mined ethereum on ethermine with ethminer, ZEC on nanopool, variety of algos on miningpollhub with variety of miners including ethereum with Claymore's dual miner; XVG on suprnova and XMR..

I've mined a variety of algos with a variety of miners with these very settings.  I'm only getting crashes with excavator and ccminer/ccminer-64 on NH for ethash and x11gost respectively. 

I don't believe my OC settings are TOO over-clocked... i've tested those limits. i know what they - and those limits produce other problems in a very short period of time.

I wonder what investigative work has been done on the code side to decipher the error 
"CUDA error 'unspecified launch failure' in func 'cuda_daggerhashimoto::run' line 1461"

**Comment by gordan-bobic** [comment]
First rule of bug reporting - try it at stock clocks. Don't report a bug until you have demonstrated a crash without OC-ing and eliminated any possibility of a hardware bug. Otherwise you are just creating more noise and wasting developers' time by sending them on a ghost hunt.

Your cards are too overclocked. I have 4x EVGA 1070Ti cards right next to me churning away. If you want 100% stability, stay at <= 8400MHz on the memory (4200MHz DDR) and <= +125 MHz core.

Anything above that won't be 100% stable. Depending on luck, you might get minutes, hours or days between crashes (to some extent affected by the ambient temperature) but it will not be completely stable. I have tested the stability limits of these cards quite extensively.

I'm not an excavator developer and thus don't have access to the source code. I suggest you go try ethminer on your hardware, and then see how long that takes to error out (it is about 3% faster and thus runs the hardware that little bit harder). You will find that it crashes out in less than a day with your OC settings. Or to put it another way, what investigative work has been done by you to be able to adamantly claim your OC is 100% stable?

**Comment by salighie** [comment]
I have mined on ethermine with ethminer with these exact configurations and i've never had a crash mining 24/7 for weeks.  I've mined a variety of algos on a variety of pools with a variety of miners with these exact configurations. Excavator and CCMiner on NH are the only miners that crash. 

Look i appreciate your input and will keep that in mind for future testing and tweaking, but i just don't agree on the basis of my experience and i don't understand where you are getting those clock speeds. 

GPU Core @ +175 yields max 1822MHz (stock is 1607 MHz)
Mem Clock @ +750 yields 4551MHz (whereas the vendor advertises 8008MHz effective as stock)
Note that they never go in P0 state - they are always in P2.

Here's the output form a ps script i wrote which utilizes Nvidia utilities to enumerate the  information:

<table><tbody><tr><th colspan="8">GPU SENSOR READOUT</th></tr><tr><th>ID</th><th>PSTAT</th><th>FAN</th><th>GPULOD</th><th>TEMP</th><th>PWR</th><th>GPUCLK</th><th>MEMCLK</th></tr><tr><td style="text-align:right">GPU 1</td><td>P2</td><td style="text-align:right;">80 %</td><td style="text-align:right;">99 %</td><td style="text-align:right;">41 C</td><td style="text-align:right;">117.04 W</td><td style="text-align:right;">1822 MHz</td><td style="text-align:right;">4551 MHz</td></tr><tr><td style="text-align:right">GPU 2</td><td>P2</td><td style="text-align:right;">80 %</td><td style="text-align:right;">99 %</td><td style="text-align:right;">39 C</td><td style="text-align:right;">115.31 W</td><td style="text-align:right;">1784 MHz</td><td style="text-align:right;">4551 MHz</td></tr><tr><td style="text-align:right">GPU 3</td><td>P2</td><td style="text-align:right;">80 %</td><td style="text-align:right;">99 %</td><td style="text-align:right;">41 C</td><td style="text-align:right;">116.79 W</td><td style="text-align:right;">1822 MHz</td><td style="text-align:right;">4551 MHz</td></tr><tr><td style="text-align:right">GPU 4</td><td>P2</td><td style="text-align:right;">80 %</td><td style="text-align:right;">99 %</td><td style="text-align:right;">40 C</td><td style="text-align:right;">118.45 W</td><td style="text-align:right;">1822 MHz</td><td style="text-align:right;">4551 MHz</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td colspan="2" style="text-align:right">TOTAL PWR DRAW:</td><td>467.59 W</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table>

**Comment by gordan-bobic** [comment]
So ccminer AND excavator both crash, and you think it's a software bug rather than OC stability issue?

The figures I'm getting are from extensive testing over many weeks. As you approach something that is almost stable crashes diminish, but I have only achieved 100% 24/7 stability for weeks at a time at no more than +125 core and no more than 4200 (8400, +5%) on memory.

If you have some kind of a watchdog setup that watches for crashes, you can run at unstable settings and have the watchdog reboot the machine when it crashes. Whether you'll lose more in reboot time than you gain in extra clock speed is something you'd have to work out for yourself. Personally, I like my mining rigs to require 0 maintenance.

Standard boost map actually goes all the way to 1999MHz, but that only happens with a very un-intensive algorithm. Fire up something like xmrig-nvidia and you'll find it'll reach that, which is ironically why CPU-light algorithms like cryptonight can actually result in worse stability.

The reason why you are seeing a discrepancy from 8008MHz is that this is the P0 level (gaming) memory clock speed. As soon as a compute intensive load is detected (high GPU load that is not writing to the frame buffer), the card will go into P2 power state which is 7600MHz. Both of these are DDR figures, the actual clock speed is half, so 4004 and 3800 respectively.
So your reading of 4551 MHz is equivalent to 9102 MHz DDR.

Either way, all of this is a waste of time on this thread. Dial back the OC and see if you get a similar crash in the next week. If you don't, that answers your question and it's not a software bug.

**Comment by dropky** [comment]
Closing this, see the comment above (https://github.com/nicehash/excavator/issues/216#issuecomment-373837969).
