### ISSUE TITLE
Excavator mining doesn't restart after GPU crash, just sits idle.

### ISSUE THREAD

**Issue by ikorzha** [nicehash/excavator#218]
Guys I have encountered the following issue  on a few of my rigs. When a GPU on a rig crashes, Nicehash restarts the Excavator but it sits idle with msg "Core Initialized" However nicehash showing "Mining" msg. Please help, I am forced to constantly monitor the rigs manually due to this problem.
Please see attached image for exact reference:

![crash](https://user-images.githubusercontent.com/11211789/37497940-b454d29e-2891-11e8-8c77-a6fe65fcb1d4.jpeg)
...

**Comment by dropky** [comment]
This looks like a NiceHash Miner issue, NHM should tell excavator to start mining after the restart. Excavator sits at "Core Initialized" because it hasn't received any mining commands (which algorithm to mine on which card). Another question is why the excavator crashes in the first place. Did you happen to see any errors before excavator restarts? What are your overclock settings for the cards?

**Comment by ikorzha** [comment]
I am pretty sure it is crashing due to unstable overclock on 1 of the 4 1080ti cards. However I do clearly understand this part that is not an issue here but symptom of the problem.
I can clearly replicate the problem:
What is disturbing to me is that if i "close" the excavator manually during mining process, it will auto restarts instantly but will sit at core initialized.
However at the sametime NHM will state that it is still mining. I pretty much must press stop and start in order for it to start again.
Can you please test and solve this problem in NHM? That is a revenue impacting bug.

**Comment by dropky** [comment]
> Can you please test and solve this problem in NHM? This is a revenue impacting bug.

I reported the issue to the NHM team.

**Comment by nicehashdev** [comment]
Not an issue. Closing.
