### ISSUE TITLE
Improve Equihash algorithm speed

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#219]
Excavator ~3860 kH/s (shouldn't be Sol/s?)

Competitors:
- [Bminer](https://bitcointalk.org/index.php?topic=2519271.0) ~4040 Sol/s
- [EWBF's CUDA Zcash miner](https://bitcointalk.org/index.php?topic=1707546.0) ~3860 Sol/s
- [dstm's ZCash Cuda miner](https://bitcointalk.org/index.php?topic=2021765.0) ~3930 Sol/s

Same rig, same settings. Tested today.

**Comment by dropky** [comment]
We're working on improvements for Equihash. 

FYI. Be careful when using Bminer - https://github.com/nicehash/NiceHashMinerLegacy/issues/908. There are multiple reports about inflated hashrate.

**Comment by lear001** [comment]
https://www.google.com/search?dcr=0&q=how+pool+calculated+hashrate&spell=1&sa=X&ved=0ahUKEwi8spLS3O3ZAhVBCpoKHbJECToQBQgkKAA&biw=1396&bih=668

https://www.bminer.me/faq/#why-the-reported-hashrate-of-bminer-is-higher-than-the-reported-hashrate-from-mining-pools

Pls check these posts to figure out why the reported hashrate is higher than the reported hashrate from mining pools, and all mining softwares have the same issues.

**Comment by apiontek** [comment]
For me, excavator is already faster than dstm on linux, when factoring in dstm's 2% fee. But yes, would love to see the same thing on the Windows side!

Something's definitely fishy with bminer, I wouldn't recommend anyone gamble with it.

**Comment by BeefBaby** [comment]
@apiontek I get "Failed to connect to miner (ExcavatorNvidia1)" everytime I try to use it with the newest Python version.

**Comment by Angel996** [comment]
I don't know why everyone is so hyped about excavator, for me it's much slower than DSTM's. I get ~ 1340 h/s on DSTM whereas around 1220 on Excavator. GPUs are 1060, 970, 1050.

**Comment by apiontek** [comment]
That's true for me on Windows. On Linux they're close enough that excavator wins when accounting for dstm's fee. And since excavator beats other miners for some other algorithms, and equihash is generally the best algorithm for Nvidia at Nicehash, that's why people are Keen for excavator to perform better than it currently does on equihash.

**Comment by Angel996** [comment]
Well, DSTM's fee is 2%, whereas difference in hashrate is 10%, as per my example.

**Comment by apiontek** [comment]
Ok? Yes? So if the difference were less than 2%, or excavator we're faster, that'd be good, no? What's your concern?

**Comment by Angel996** [comment]
That'd be good, exactly. :-)

**Comment by joseortiz3** [comment]
@apiontek 
Interesting! How did you get excavator to be faster than dstm on linux? I was not aware this was possible. 

How did you compile? Or did you use an internet-downloaded binary? If you compiled, which Cuda version and gcc version did you use? Thanks.

**Comment by apiontek** [comment]
Well, obviously YMMV but this is my situation and results:

Ubuntu 17.10, kernel 4.13.0-37-generic
Nvidia 390.30-0ubuntu1, cuda 9.1.85-1
GTX 1070 GPU
i7-4790 CPU
ewbf 0.3.4b
dstm 0.6
excavator 1.4.4a_nvidia

(I don't think we can compile excavator, can we? This github is just for info & releases, there's no source, right?)

For me, with no overclocking I get the following (30 minute averages)

**ewbf:**
run command: ~/mining/bin/ewbf/miner --fee 0 --tempunits C --solver 0 --user 1bitcoinaddress1bitcoinaddress.worker --pass x --server equihash.usa.nicehash.com --port 3357 --eexit 3 --pec --api
30 min average: 424.24 Sol/s

**dstm:**
run command: ~/mining/bin/dstm/zm --server equihash.usa.nicehash.com --port 3357 --user 1bitcoinaddress1bitcoinaddress.worker --pass x --noreconnect --telemetry
30 min average: 431.80 Sol/s

**excavator:**
run command: /usr/bin/excavator -p 3456 -na -c excavator_equihash_nicehash.json
30 min average: 424.80 Sol/s

I'll share the contents of my excavator_equihash_nicehash.json below. For now, just note that while dstm is _faster_ it's only faster by 1.6%, which you lose in fees, and neither excavator nor ewbf (with the --fee 0 argument) have fees. So, in this case, for me, excavator wins.

dstm sometimes spikes higher, but it also drops lower. They all do, really. That's why I test over a long time, sampling the hashrate from the API every 15 seconds and averaging out over time.

When I pump up my overclocking to 150/500, I get:

ewbf: 452.74
dstm: 464.16
excavator: 456.85

Again, dstm is _faster_ but only by 1.6%, so on average over time I earn more with excavator when accounting for the 2% fee.

**Comment by Angel996** [comment]
apiontek, I wonder why your results are so different from mine. Couldn't be Linux version, I run 16.04 LTS.

Are you mining on a single GPU? That could be a bit different. You know, PCIE bandwidth *Does* affect hashrate too. And it tends to get worse per card once you install additional GPUs.

**Comment by apiontek** [comment]
I only have one GPU in this machine, yes. Yes, with your results I'd be using dstm.

**Comment by apiontek** [comment]
I take it back. When I look at the hashrates actually reported on pools, including Nicehash, excavator isn't the best anywhere. In fact, for me, ewbf with 0 fee option comes out on top. Seems to me the hashrate the pool sees over time is more important than what the miner says it's doing.

**Comment by borzaka** [comment]
@apiontek That's right. You are payed based on the hashrate what the pool sees, not what the miner shows.

**Comment by igorvoltaic** [comment]
Regarding Bminer. I've setup a small pool. Bminer's reported hashrate is ~2070sol/s, on pool side (which is what really important) it is ~2004sol/s. DSTM's only gives me ~1950-1980sol/s and ewbf is only ~1880sol/s. It is more stable. I think i need to give excavator another try and post it here.

I've got 4xGTX1060 & 1xGTX1080ti on centos7 linux rig. cuda 9.1 and latest nvidia driver.

**Comment by dropky** [comment]
I'm closing this thread due to equihash ASICs.

**Comment by borzaka** [comment]
Bitcoin Gold will have a [Network Upgrade](https://bitcoingold.org/bitcoin-gold-network-upgrade/) in less than two days. The main goal for the network upgrade is to prevent current ASICs from mining.
Probably more coins will follow.

Maybe the same thing is happening as with the CryptoNight algo?

**Comment by joseortiz3** [comment]
@dropky Nicehash will continue experience an exodus of GPU miners if the new algorithms are not supported quickly. Switching to new algorithm support should be first-priority for NiceHash at this point, unless you guys want to rely on asic alone.

**Comment by dropky** [comment]
I'll see what I can do.
