### ISSUE TITLE
Explanations to the algorithm of work

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#244]
I noticed that 1.5 is significantly different from 1.4
For example, deleting the algorithm now does not lead to the removal of the workers.

You can get a detailed description of the sequence of work with the API? And especially the interaction of different methods.

I need a command sequence description: 
1. Algorithm change  (with existing subscription and running algorithm and running workers).
2. Subscribe change (with existing subscription and running algorithm and running workers).

Thank you in advance!

**Comment by EvgeniyKorepov** [comment]
I found one of the reasons for my problems:
if you send two commands unsubscribe and subscribe - Excavator goes crazy. Fixes the problem with a small timeout (200-300 ms) between commands.

**Comment by MichaelMiner** [comment]
Жень, зря мучаешься, только время своё убиваешь!
Пройдёт год, пока они всё исправят.
Я забросил его, а если надо, то пользуюсь 1,4

**Comment by EvgeniyKorepov** [comment]
@MichaelMiner ну мне нравятся сложные задачи, хобби у меня такое - ломать себе мозг ;-)

**Comment by dropky** [comment]
> I need a command sequence description:
> 
> Algorithm change (with existing subscription and running algorithm and running workers).

The sequence of commands needed for switching:
- worker.clear() or worker.free()
- algorithm.clear() or algorithm.remove()
- algorithm.add()
- worker.add()

The only difference from the API in 1.4.* versions is that algorithm.remove/clear method doesn't free the assigned workers as well, you have to clear them on your own. 

> Subscribe change (with existing subscription and running algorithm and running workers).

From version 1.5.2a in order to change subscription you only have to call subscribe method one more time (we fixed the issue with the multiple subscribe calls, if you call subscribe method and you're already subscribed excavator will automatically unsubscribe and then subscribe with the new btc address). Here is the cmd file example:

```
[
    {"time":1,"commands":[
       {"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","btc"]}
    ]},
    {"time":2,"commands":[
        {"id":1,"method":"algorithm.add","params":["keccak"]}
    ]},
    {"time":3,"commands":[
	{"id":1,"method":"worker.add","params":["keccak", "3"]}
    ]},
    {"time":30,"commands":[
       {"id":1,"method":"subscribe","params":["nhmp.eu.nicehash.com:3200","different_btc"]}
    ]}
]
```

**Comment by EvgeniyKorepov** [comment]
@dropky  please publish all the answers in the new field server_status of the method subscribe.info
- Subscribed
- Not subscribed
- ????????????
or there are only two options?

**Comment by dropky** [comment]
Server_status is returning messages from the stratum server (exceptions are "Subscribed" and "Not subscribed" messages). Not subscribed means that subscribe method hasn't been called yet. 

Its main purpose is to figure it out the reason why the subscription was terminated ("Invalid BTC address", "WebSocket connection closed normally",.. ). You should check this field if connected response is False.

Note that "WebSocket connection closed normally" is not an error. It can happen if there are no active algorithms or if miner hasn't found a share in more than 10 minutes. In such case excavator will reconnect and continue mining.

**Comment by dropky** [comment]
You need to periodically call subscribe.info method in order to check if excavator is still connected to the stratum (you can do that with checking connected field). If True everything is ok, if False then you should check server_status; If the message is "WebSocket connection closed normally" wait for a second or two and check the info status again; If it's still disconnected after a couple of seconds, try changing the stratum location - call subscribe method with different stratum addr;

**Comment by EvgeniyKorepov** [comment]
@dropky Thank you, everything is clear!
