### ISSUE TITLE
missing Linux builds for v1.6.x

### ISSUE THREAD

**Issue by lesinigo** [nicehash/excavator#284]
Will be there any Linux build for the new release series?

**Comment by nicehashdev** [comment]
Unfortunately, there is a lot of platform specific code related to NVIDIA device management (overclocking, fans etc..) which would perhaps need a bit of reverse engineering on Linux. At this point in time, I am unable to take care of everything thus there will be no builds for Linux for some time. When (if) we find a developer who could handle this part, we will provide Linux binaries.

We are well aware that recent version of Excavator is achieving same speeds as competition, but does not have any devfee, so it is reasonably desired miner. For the time being, I suggest using Windows. According to my tests, rigs are fully stable for days/weeks using Excavator with provided auto restart script.

**Comment by lesinigo** [comment]
are you saying Excavator on Windows is recommended over NHOS which is linux-based?

**Comment by nicehashdev** [comment]
Currently, Excavator is very good miner. It has same speed (if not better) compared to other miners that require devfee to be paid. It has no devfee, all your hashrate goes to NiceHash. Additionally to that, it supports overclocking, fan control, it has watchdog (experimental), windows service startup (experimental) and experimental octuner tool to really maximize your GPUs. It is everything you need as a miner. You do not need to install any other tool (no MSI Afterburner is needed). Excavator will act in a smart way, generating DAG with non-OC memory, so it doesnt get corrupted - you can therefore have higher memory OC when mining thus achieving even higher speeds. It communicates over custom protobuff protocol, SSL encrypted to port 443 (websockets), so it cannot get blocked by routers or ISPs, because the traffic looks just like a legit HTTPS website traffic.

There are probably other good features I have forgotten to mention, but you probably get the picture, no?

**Comment by mberk** [comment]
It sounds great but no one in their right mind would switch from using Linux to Windows so please consider this another vote for Linux builds

**Comment by lesinigo** [comment]
As @mberk said... and there's also the licensing issue: anyone coming from NHOS or the linux version of old Excavator would need to buy licenses for Microsoft Windows. Missing a Linux build will draw more people to NHOS or third party solutions.

**Comment by sharkguto** [comment]
@nicehashdev is not possible to create a .deb without implement direct overclocking and fan control.??? it would be great we have a simple version of it.

**Comment by gilvbp** [comment]
> @nicehashdev is not possible to create a .deb without implement direct overclocking and fan control.??? it would be great we have a simple version of it.

@nicehashdev 
Just like you did with 1.5.14 alpha?

**Comment by sharkguto** [comment]
@nicehashdev please :)

**Comment by nicehashdev** [comment]
Linux builds are on TODO. Closing.
