### ISSUE TITLE
Higher MH/s on Eth for 3060s, but more rejected shares

### ISSUE THREAD

**Issue by BigGayLucy** [nicehash/excavator#313]
I really like excavator, it has a 0% devfee, and is one of the first to optimize 3060 Eth mining. I get a higher hashrate on excavator then on NBminer for example. But sadly I get more ''Above target'' rejected shares then on NBMiner with the exact same OC settings.
My second 3060 with a 200+ Core clock and 1350 Mem clock OC gets 0.16-0.32 rejected shares with practically 0 above target rejected shares. For excavator I'd get about 3.26-4% above target rejected shares with the exact same OC. Downclocking the memory clock to 1100, reduced the above target rejected shares to about 1.2-1.5%. Incl. this into my calculations, despite the lower devfee, it would still be less profitable.

For some reason it is specifically on my second GPU only. Not my first, I run a 160+ Core clock OC and 1410+ Mem clock OC on my primary GPU, which seems to get 0 errors on Excavator. Which is great since it would get more on the likes of NBminer.

 I hope you can fix it. If you need more details about my system, Ill share. (Meanwhile running my second card with a miner like TRex or NB has fixed the problem, I am getting 0.16% rejected once more)

**Comment by nicehashdev** [comment]
There is nothing to be fixed. The share above target happens due to mistakes in memory data - returned value is not correct. This leads to invalid calculation which causes invalid share. Solution - as you know - is to reduce these mistakes which can be done by making VRAM more stable which means reducing overclock.

You should be running Excavator as administrator so it can lower memory OC during DAG generation phase - this greatly eliminates chance of DAG data being corrupt in any way. When Excavator is used with NiceHash QuickMiner, there are usually no issues with shares above target because DAG phase is well taken care of.

Another thing I would suggest you to actually decrease core clock and not increase. Increased core clock leads to more instability and higher chance of invalid shares. Using alternative OC from OCTune appears to be the best way to optimize Ampere cards for mining.

**Comment by BigGayLucy** [comment]
Atleast there is something to be improved. Like I said, I get none of those rejected shares when running the card on TRex or NBminer. I currently run my second GPU on TRex miner with my primary on excavator. And I once again have only 0.08-0.3% rejected shares with no above targets.

Now I do not have to reduce the OC. So I get more profit
