### ISSUE TITLE
Throttle Excavator server

### ISSUE THREAD

**Issue by harames2001** [nicehash/excavator#74]
Hey there, i tryed to throttle the excavator server to use only 50% GPU.
Useing GTX1080
I changed the "default_command_file.json" file to:
[
        {"time":1,"commands":[
		{"id":1,"method":"algorithm.add","params":["equihash","equihash.eu.nicehash.com:3357",""]}
	]},
	{"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]}
	]},
	{"time":5,"commands":[
		{"id":1,"method":"device.set.tdp","params":["0","50"]}
	]},
	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
	  	{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
]
After i started the mining the gpu is working 100%. WHY? What i am doing wrong?
THX for the fast help.

**Comment by dropky** [comment]
There is nothing wrong with the config file. This should work.

Which OS are you using? Could you post log file with -f 0?

**Comment by Kayfolom** [comment]
{"id":1,"method":"device.set.tdp","params":["0","50"]}  Limits the power consumption of the GPU in 50% (not only for mining, but for OS functions), the download will still be 100%.
https://github.com/nicehash/excavator/tree/master/nvidia#equihash :
To manage intensity of this algorithm, we suggest you to run only one worker to reach low intensity and multiple (suggest 2) workers per device to reach optimal speed.

Maybe you'd better use a ccminer with intensity adjustment?

**Comment by harames2001** [comment]
Can i use 2 workers on one GTX1080 device?

**Comment by dropky** [comment]
Remark on your config file: 

You don't have to add Equihash twice in order to run it on multiple workers.  Your config file should look like this:

```
[
	{"time":1,"commands":[
		{"id":1,"method":"algorithm.add","params":["equihash","equihash.eu.nicehash.com:3357","***"]}
	]},
	{"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","0"]}
	]},
	{"time":5,"commands":[
            {"id":1,"method":"device.set.tdp","params":["0","50"]}
	]},
	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"worker.print.speed","params":["1"]},
  		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
]
```

"I have to workers. Now i add "-cd 1" in the .bat file":

Please take a look into our documentation on command line parameters - https://github.com/nicehash/excavator#-command-line-parameters, cd doesn't do anything.

To run the algorithm on selected device you need to properly modify worker.add method -
 https://github.com/nicehash/excavator/tree/master/api#worker-add .

For example:  
`{"id":1,"method":"worker.add","params":["0","0"]}` - run alg 0 on device 0
`{"id":1,"method":"worker.add","params":["0","1"]}` - run alg 0 on device 1

If you would like to run 2 workers on device 1, change the worker.add commands to:
```
{"time":3,"commands":[
	{"id":1,"method":"worker.add","params":["0","1"]},
	{"id":1,"method":"worker.add","params":["0","1"]}
]},
```

Note on Equihash: We suggest to run multiple workers only with M=0 parameter, otherwise you should get the optimal performance with one worker. 

To run Equihash with M=0 parameter, change the worker.add methods to:
```
{"time":3,"commands":[
	{"id":1,"method":"worker.add","params":["0","1","M=0"]},
	{"id":1,"method":"worker.add","params":["0","1","M=0"]}
]},
```
