### ISSUE TITLE
CUDA error 'an illegal instruction was encountered' in func 'cuda_neoscrypt:run' line 1328

### ISSUE THREAD

**Issue by seanvetter** [nicehash/excavator#85]
#### System Spec: ####
* Windows 10
* 6x evga 1060 6GB
  * Core clock: +100
  * Memory clock: +600, +575
* Nvidia Driver: 388.13
* 8GB Memory
* 36GB Pagefile
* Nice Hash 2.0.1.5 - Beta

#### Summary ####
I have been getting occasional crashes in excavator that just end up restarting things. Not a huge deal but I have been trying to track down the error message and figure out if it's a bug or overclock issue(this is possible but I'm not sure what the symptoms are). I have attached a screenshot of the error that pops up in the terminal let me know if you would like more logs. It would be great if there was an easy way to dump the terminal output to a file or increase the log level because when it restarts I lose the error message. There probably is I just don't know what config file to edit(mind sharing some knowledge?). I can't say for sure if it's always neoscrypt that causes the crash but it could be and that is the error I caught this time. 

#### Screenshot ####
![screenshot 2017-12-05 19 34 06](https://user-images.githubusercontent.com/15274136/33643657-59ced404-d9f5-11e7-8a81-82f43fd4f87e.png)

**Comment by dropky** [comment]
To 'dump terminal output' into file please change file log level to 0. You have to edit General.json file located in `C:\Users\user_name\AppData\Roaming\nhm2\configs\General.json`. Set ExcavatorExtraStartupParameters to -f 0 (`"ExcavatorExtraStartupParameters": "-f 0"`).  You can find Excavator's logs in `C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_server\archived_logs`. 

Note: you'll have to restart NHM2 in order to apply the changes. 

(Also you'll have to wait till NiceHash is back online)

If this happens only with neoscrypt I suggest that you disable it. We're working on some improvements/fixes, till then occasional crashes can occur since the algorithm is extremely memory hard.
