### ISSUE TITLE
CUDA error driver 700

### ISSUE THREAD

**Issue by feernandobraga** [nicehash/excavator#93]
Hi there,
I've been running excavator to mine lyra2rev2 algorithm and I'm experiencing some crashes on the miner.
I've attached a couple of logs to see if maybe you guys can help me to identify the problem.
I'm running 4 gtx 1070 on windows 10 with the latest drives.
[log_2017-12-11_18-50-43.002.log](https://github.com/nicehash/excavator/files/1550688/log_2017-12-11_18-50-43.002.log)
[log_2017-12-11_20-05-56.005.log](https://github.com/nicehash/excavator/files/1550689/log_2017-12-11_20-05-56.005.log)

**Comment by Kayfolom** [comment]
Use one vorker on the GPU.
Here is an example configuration:

**Comment by feernandobraga** [comment]
Hi @Kayfolom, thank you for your very quick reply.
I have to be honest, and I have no idea what you just told me to do ):
Is it possible for you to explain to me where I should use that code? Also, if I copy and paste what you just wrote, will it works on my rig or it's just a general example?
Thank you and sorry for asking for more.

**Comment by dropky** [comment]
What @Kayfolom told you is to use one worker per device, not two. This looks like an overclocking problem though, I suggest you to run at default GPU settings and then change the settings (memory clock, core clock and power limit) until you find the stable state. 

Here is an example that should work (you have to change ***************** to your username:password). You can take a look at our documentation - https://github.com/nicehash/excavator/tree/master/api#-algorithmadd .  

```

[ {"time":1,"commands":[ 
	{"id":1,"method":"algorithm.add","params":["lyra2rev2","mona.suprnova.cc:2997","*****************"]} 
]}, 
{"time":2,"commands":[ 
	{"id":1,"method":"worker.add","params":["0","0"]}, 
	{"id":1,"method":"worker.add","params":["0","1"]}, 
	{"id":1,"method":"worker.add","params":["0","2"]}, 
	{"id":1,"method":"worker.add","params":["0","3"]} 
]}, 
{"time":10,"commands":[ 
	{"id":1,"method":"worker.reset","params":["0"]}, 
	{"id":1,"method":"worker.reset","params":["1"]}, 
	{"id":1,"method":"worker.reset","params":["2"]}, 
	{"id":1,"method":"worker.reset","params":["3"]} 
]}, 
{"time":15,"loop":20,"commands":[ 
	{"id":1,"method":"worker.print.speed","params":["0"]}, 
	{"id":1,"method":"worker.print.speed","params":["1"]}, 
	{"id":1,"method":"worker.print.speed","params":["2"]}, 
	{"id":1,"method":"worker.print.speed","params":["3"]}, 
	{"id":1,"method":"algorithm.print.speeds","params":["0"]} 
]}
]
```

Since you were asking where should you use this code I'll briefly explain that as well. You can copy the code above into config.json file and then run excavator.exe with -c conifg.json parameter.

Please take a look into our documentation and config file examples.

**Comment by feernandobraga** [comment]
Thank you so much for clarifying it @dropky.
Hope you have an awesome day <3
